name: "Create Release Note"

inputs:
  commits:
    description: "All commit messages from the commit changes"
    required: true
  delimiter:
    description: "Delimiter for the commits string"
    required: false
    default: "|||"
  version:
    description: "Version of the Releasing Library"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/update-changelog.sh
      shell: bash
      env:
        COMMITS: ${{ inputs.commits }}
        DELIMITER: ${{ inputs.delimiter }}
        VERSION: ${{ inputs.version }}