name: "Create Release"
on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 20

    - name: "Log GitHub context"
      run: |
        echo "PR was merged....."
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    
    - name: "Git log"
      run: |
        echo "GIT_SHA=${GIT_SHA}"
        COMMITS=$(git log --pretty=format:"- %s" ${GIT_SHA}^1..${GIT_SHA})
        echo "$COMMITS"
      env:
        GIT_SHA: ${{github.sha}}
    
    - name: "Get PackageJson"
      id: get-package-json
      run: |
        PACKAGE_JSON=$(cat package.json)
        echo "PACKAGE_JSON=${PACKAGE_JSON}" >> $GITHUB_OUTPUT

    - name: "Get New Version"
      id: get-new-version
      run: |
        echo "CURRENT_VERSION=${CURRENT_VERSION}"
        NEXT_VERSION=$(npx semver ${CURRENT_VERSION} minor)
        echo "NEXT_VERSION=${NEXT_VERSION}"
        echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_OUTPUT
      env:
        CURRENT_VERSION: ${{ fromJson(stpes.get-package-json.outputs.PACKAGE_JSON).version }}

    # - name: "Create release pr"
    #   run: |
    #     gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}