name: "Update GitHub Release"
on:
  push:
    branches: 
      - release/*

jobs:
  update-github-release:
    # if: ${{ !startsWith(github.event.head_commit.message, '[Automated] Release version') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Get PackageJson"
      id: get-package-json
      run: |
        PACKAGE_JSON=$(cat package.json | tr -d '\n')
        echo "PACKAGE_JSON=${PACKAGE_JSON}" >> $GITHUB_OUTPUT

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Create GitHub Release
      run: |
        EXTRACTED_RELEASE_NOTE=$(awk -v ver="${VERSION}" '
          $0 ~ "^## \\[" ver "\\]" {
            found=1
            next
          }
          found && /^## \[/ {
            found=0
          }
          found {
            print
          }
        ' "${CHANGELOG_FILE}")

        echo "EXTRACTED_RELEASE_NOTE=${EXTRACTED_RELEASE_NOTE}"
        ${UPDATE_OR_CREATE_GH_RELEASE}
      env:
        VERSION: ${{ fromJson(steps.get-package-json.outputs.PACKAGE_JSON).version }}
        CHANGELOG_FILE: "CHANGELOG.md"
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        UPDATE_OR_CREATE_GH_RELEASE: |
          ${{ startsWith(github.event.head_commit.message, '[Automated] Release version')
            && 'gh release create ${VERSION} -d -t "Release ${VERSION}" --notes "${EXTRACTED_RELEASE_NOTE}"'
            || 'gh release edit ${VERSION} --notes "${EXTRACTED_RELEASE_NOTE}"'
          }}