name: "Update GitHub Release"
on:
  push:
    branches: 
      - release/*

jobs:
  update-github-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Get PackageJson"
      id: get-package-json
      run: |
        PACKAGE_JSON=$(cat package.json | tr -d '\n')
        echo "PACKAGE_JSON=${PACKAGE_JSON}" >> $GITHUB_OUTPUT

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Extract Release Note
      run: |
        EXTRACTED_RELEASE_NOTE=$(awk -v ver="${VERSION}" '
          $0 ~ "^## \\[" ver "\\]" {
            found=1
            next
          }
          found && /^## \[/ {
            found=0
          }
          found {
            print
          }
        ' "${CHANGELOG_FILE}")

        echo -e "$EXTRACTED_RELEASE_NOTE" > release-note-temp.md
      env:
        VERSION: ${{ fromJson(steps.get-package-json.outputs.PACKAGE_JSON).version }}
        CHANGELOG_FILE: "CHANGELOG.md"

    - name: Create GitHub Release
      if: ${{ startsWith(github.event.head_commit.message, '[Automated] Release version') }}
      run: |
        gh release create v${VERSION} -d -t "Release v${VERSION}" --notes "${EXTRACTED_RELEASE_NOTE}" --notes-file release-note-temp.md
        rm release-note-temp.md
      env:
        VERSION: ${{ fromJson(steps.get-package-json.outputs.PACKAGE_JSON).version }}
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Update GitHub Release
      if: ${{ !startsWith(github.event.head_commit.message, '[Automated] Release version') }}
      run: |
        gh release edit v${VERSION} --notes "${EXTRACTED_RELEASE_NOTE}" --notes-file release-note-temp.md
        rm release-note-temp.md
      env:
        VERSION: ${{ fromJson(steps.get-package-json.outputs.PACKAGE_JSON).version }}
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}