name: "Release"
on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 20

    - name: "Log GitHub context"
      run: |
        echo "PR was merged....."
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    
    - name: "Git log"
      run: |
        echo "GIT_SHA=${GIT_SHA}"
        COMMITS=$(git log --pretty=format:"- %s" ${GIT_SHA}^1..${GIT_SHA})
        echo "$COMMITS"
      env:
        GIT_SHA: ${{github.sha}}
