name: "Create Release PR"
on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
    types:
      - closed

jobs:
  create-release-pr:
    if: ${{ github.event.pull_request.merged && github && !startsWith(github.head_ref, 'release/')}}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Log GitHub context"
      run: |
        echo "PR was merged....."
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: "Get PackageJson"
      id: get-package-json
      run: |
        PACKAGE_JSON=$(cat package.json | tr -d '\n')
        echo "PACKAGE_JSON=${PACKAGE_JSON}" >> $GITHUB_OUTPUT

    - name: "Get New Version"
      id: get-new-version
      run: |
        echo "CURRENT_VERSION=${CURRENT_VERSION}"
        echo "TAG=${TAG}"
        NEXT_VERSION=$(npx semver ${CURRENT_VERSION} -i ${TAG})
        echo "NEXT_VERSION=${NEXT_VERSION}"

        echo "TAG=${TAG}" >> $GITHUB_OUTPUT
        echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_OUTPUT
      env:
        TAG: ${{ contains(github.event.pull_request.labels.*.name, 'major') && 'major' || contains(github.event.pull_request.labels.*.name, 'patch') && 'patch' || 'minor' }} 
        CURRENT_VERSION: ${{ fromJson(steps.get-package-json.outputs.PACKAGE_JSON).version }}

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 20
        ref: main
        token: ${{ steps.app-token.outputs.token }}
    
    - name: "Git log"
      id: get-git-log
      run: |
        echo "GIT_SHA=${GIT_SHA}"
        COMMITS=$(git log --pretty=format:"%s" ${GIT_SHA}^1..${GIT_SHA} | sed ":a;N;$!ba;s/\n/${DELIMITER}/g")
        echo "COMMITS=$COMMITS"
        echo "COMMITS=$COMMITS" >> $GITHUB_OUTPUT
      env:
        GIT_SHA: ${{github.sha}}
        DELIMITER: "|||"

    - name: Get GitHub App User ID
      id: get-user-id
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.app-token.outputs.token }}
        script: |
          const result = await github.rest.users.getByUsername({
            username: '${{ steps.app-token.outputs.app-slug }}[bot]'
          })
          return result.data.id

    - name: Config git
      shell: bash
      run: |
        git config user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
        git config user.email "${{ steps.get-user-id.outputs.result }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"

    - name: Create release branch
      id: create-branch
      shell: bash
      run: |
        git checkout -b ${BRANCH_NAME}
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
      env:
        BRANCH_NAME: release/${{ steps.get-new-version.outputs.NEXT_VERSION }}

    - name: Update version
      run: |
        npm version ${TAG} --no-git-tag-version
      env:
        TAG: ${{ steps.get-new-version.outputs.TAG }}

    - name: Run Create Release Note
      uses: tanatip-boonloy-org/test-github-features/.github/actions/release@main
      with:
        commits: ${{ steps.get-git-log.outputs.COMMITS }}
        version: ${{ steps.get-new-version.outputs.NEXT_VERSION }}
    
    - name: Commit & Push Changes
      run: |
        git add package.json package-lock.json
        git add CHANGELOG.md
        git commit -m "[Automated] Release version ${VERSION}"
        git push origin ${BRANCH_NAME}
      env:
        VERSION: ${{ steps.get-new-version.outputs.NEXT_VERSION }}
        BRANCH_NAME: release/${{ steps.get-new-version.outputs.NEXT_VERSION }}

    - name: "Create release pr"
      run: |
        gh pr create -H ${BRANCH_NAME} -B main --title "Release ${NEXT_VERSION}" --body ''
      env:
        NEXT_VERSION: ${{ steps.get-new-version.outputs.NEXT_VERSION }}
        BRANCH_NAME: ${{ steps.create-branch.outputs.BRANCH_NAME }}
        GIT_LOG: ${{ steps.get-git-log.outputs.COMMITS }}
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
